### ISSUE TITLE
Error info in the failed runs

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/trailblazer-ui#1]
Hi,

The new trailblazer looks great and feels great to use, in a very snappy en fresh way. A true glow up! However I would like to say that I am missing the error information that was available in the old version of Trailblazer. As someone who works with errors daily I really enjoyed the ease to get a point of where to start, or at least where I should not start, looking for errors.

**Comment by elevu** [comment]
**Errors added!** 

<img width="427" alt="Screen Shot 2020-09-11 at 10 46 33" src="https://user-images.githubusercontent.com/6919697/92898445-45796000-f41e-11ea-950f-dd4562b581de.png">

**Comment by karlnyr** [comment]
Awesome!
