### ISSUE TITLE
Error when the case name is a subset of another casename

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/trailblazer-ui#17]
For the case "inpig" trailblazer display ticket number and apptag för the case "mainpiglet". Seems like the regexp need to be improved somewhere (ma-INPIG-let), inpig is a subset of mainpiglet.

**Comment by elevu** [comment]
Fix'd! https://trailblazer.scilifelab.se/243899 Hard reload the page if you don't see the changes
