### ISSUE TITLE
Flag for priority cases

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/trailblazer-ui#2]
Hi,

In production we often treat priority cases first thing, and to do this it would be really nice if we would be able to see, or even filter, for priority cases. The old trailblazer had no way to filter for prio samples, however it had a tag on the name marking it as one.

**Comment by elevu** [comment]
Thank you for the feedback Kalle! I added a filterable column with priority tag. Refresh the cache if you don't see it :) 
<img width="321" alt="Screen Shot 2020-09-14 at 09 11 12" src="https://user-images.githubusercontent.com/6919697/93054840-4acaea80-f66a-11ea-8996-47ad3c66db07.png">
