### ISSUE TITLE
Set analysis status manually

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/trailblazer-ui#23]
Add functionality to edit analysis status manually from the UI -> (COMPLETED/FAILED)

Reason:
Production members should be able to set failed analyses to COMPLETED - if they evaluate the failed jobs as non-essential to performing delivery. This will simplify balsamic delivery, as currently we have much more convoluted ways to decide that an analysis is finished/is deliverable
It is also desirable to be able to set status to FAILED if SLURM is to lose track of job ID's and can no longer update Trailblazer of their status (SLURM only keeps the data for 2 days)

**Comment by elevu** [comment]
done

**Comment by Mropat** [comment]
Awesome work :partying_face:
