### ISSUE TITLE
bug, refreshing page throws error 403

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/trailblazer-ui#24]
Opening Stats page:
![image](https://user-images.githubusercontent.com/1086877/97734309-499a3380-1ad9-11eb-992a-393eb0e618c3.png)

After refreshing the page:
![image](https://user-images.githubusercontent.com/1086877/97734378-620a4e00-1ad9-11eb-992f-e399d51fe2dd.png)

Re-logging solves it though.

**Comment by elevu** [comment]
@hassanfa do you use this Stats page a lot?
After asking to some of the production people I was going to remove it. But if you use, I will keep it :)

**Comment by hassanfa** [comment]
No I don't. But if is there a way to think about exporting it in future, I'd like to trend those in Vogue.

I guess close it for now.

**Comment by elevu** [comment]
Great!

**Comment by elevu** [comment]
The page is removed
