### ISSUE TITLE
Row move after you have left comment (this is not preferred)

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/trailblazer-ui#4]
The new way of sorting rows in trailblazer is great! However, it is not optimal that rows change position directly after a comment is added.

Is it possible to change so directly after you leave a comment the order of the rows will stay the same, and first when you refresh, or apply new sort filters, then the rows will be sorted again?

**Comment by elevu** [comment]
Unfortunately that is pretty hard to do without completely changing the behaviour of the table and sorting. 
I wonder if there is a better way in the UI to highlight analyses without comments?

**Comment by henningonsbring** [comment]
If it is too complicated then I guess we have to get used to this new behaviour! I am sure there are things with higher priority to fix
