### ISSUE TITLE
Sort options in more columns

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/trailblazer-ui#5]
It would be easier for us in production if we were able to sort for both status and comment at the same time to be able to see for example the ones that has no comment yet in the comment column.  And also other fileds as Type.
Things we usually want to search for is empty comment field and top-ups.

**Comment by elevu** [comment]
Sorting at the same time on several column it is a bit complicated and could be source of a lot of bugs if done on a simple table like this. A more advanced system of filters would need be to be added.
On the other hand, there is the Status filtering and Comment sorting that can be used at the same time. I see now that the sorting of the comment doesn't work so well so I will fix it. Once that is fixed, is it enough to filter on the status after sorting by comment? 
> And also other fileds as Type.

I can add the filtering on Type

>Things we usually want to search for is empty comment field and top-ups.

What is a top-up?

**Comment by elevu** [comment]
I added a Comment filter to exclude analyses with comments. And I added sorting for status.
![Screen Shot 2020-09-30 at 14 31 34](https://user-images.githubusercontent.com/6919697/94685495-c646c000-0329-11eb-99bd-d23a90fd224f.png)
This should be enough to select analyses efficiently, but let me know if you want me to change this solution!
